language: node_js
node_js:
- 4
- 6  # recommended version
- 7
branches:
  except:
  - gh-pages
  - lightning-talk
  - l10n_develop
addons:
  code_climate:
    repo_token:
      secure: NC3ew4c92DO4SAdbJvaZkaRnEZaZcAr9NcxOeraqAKHRXY3COnerWGR8+kIE9KiadcRdatmu0sSjWldDcAZfmMwOraMI9CDkqdPSjtjciCVEFdGi+OPOvMY/gOJU6XeM7lsO5MvYD7mqChl2gR6s7IO/klPahf53c97PPDo3C90=
  sauce_connect: true
before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"
- rm -rf node_modules
- chmod +x ./test/sauceLabsTests.sh
before_script:
- npm install grunt-cli -g
- npm install bower -g
after_success:
- "./node_modules/.bin/lcov-result-merger 'build/reports/coverage/*/lcov.info' 'build/reports/coverage/lcov_merged.info'"
- "./node_modules/.bin/codeclimate-test-reporter < ./build/reports/coverage/lcov_merged.info"
- "./test/sauceLabsTests.sh"
env:
  global:
  - secure: qT8aMCYSV2rLyn0csYUkPGABuj97LV30oK6hAMCLZJA3knU+uGj1+5vtkCF+5tVYHCVOYxaaBfARfB/6y/nG+sxwZyUrYfOvM1xozwaQnI+/V2hPv22msTC/9cW7I9RwyNxydxT7Rredbdhpi/5W6Wx7e7ARTbsdi7QYDMA/FOk=
  - secure: oKuecH+rXXiHdUL/ARWFXZ6FM8K/ASxIEpI44tDujSmJtgCMjgnsl3+GtF7e5EJGjfkNDDot09bsBboLqpFJeGXSVPSKtxtrRefnb8Ld0EpdlD3L7a9f6IHF7tmMZi2YxtJE80bLD6Tp/+Yz3Luqe+EydUjbn6OYFubF5+UcjqE=
notifications:
  email:
  - secure: ADLqaNm7lR8sgCkSz7eWtWdm8zZ9OsbkcQAi2nm7hQPWAkTWPfr9qeOBh39Z3PZvkgDdlUpNZc/uPlcEGEILznJRF3HlQjWrWksNNtY3xaRc01B4uXlDbODjttb6v9mOqkwUqRfQLeerOqNynNSkT129+mz4FANn0+oucZ3EuQc=
  - secure: HhhSoqY87yd8Hkt+cfXk9XXDJeWViYQoPq8f7SJofkwSWtxfOS9GNbOUehZJDqjBMARoGi3SJBImRbisnwfMcEhKpSZs2S4Osdwk2Ayy0h8V/O+qHhiEuJq1mPbAWrYNGQerz16Ec4SbX6hPnAEle2SUwjbPUnfRRCROsJqfm0o=
  webhooks:
    urls:
    - secure: QZ3/2h7hThg527PX1z7kTTRGL5jEbTTHRbetYHt8Gzgdhvtruq4cjxMQZdUcmxKlncAhoB976iFl/Ja9EpExgrXnt/Tj0Aft6JDc7g8y0kuD/SiQpFT7d46R7vOTJeFHyMzfQN9M/h81DXrG+VO5OPGR/QYNa39kMzkTc86tt1E=
    on_success: change
    on_failure: always
    on_start: never
  slack:
    rooms:
      secure: bQlLJ6OvyWUWO51eYjPlEwuGApdYEsqBa8He4gKcTFdjTE6lLxrdu0QE6y1iIroN5+QOk4QpwIYaeWxhgrtVqTNrq9iWnhRR8agcXMPBh1cHnh8EZO6yuC3JE1dd2syKe5Vds67w6KbJedX5GNRg2SVLrL2mHq2syvWAD17BcoI=
    on_success: change
    on_failure: always
    on_start: never
before_deploy:
- rm -rf node_modules
- npm install --production
- grunt package
deploy:
- provider: heroku
  api_key:
    secure: haABq1BRLYElRq+V+7knDlMDBMMIj2aASOSdm6JFYwQa1C60nO2rWkRXBk2j3H/NSjIDamOgBzelZNfuYwnmVUrL25SEWflM1ydDGM2RmgEx0mOu6sCtz8gugOVDBTsBrc0OLcwY7trEQBlKbr+xdD1aATDLfAD+pK4SZt233gg=
  app:
    master: juice-shop
    develop: juice-shop-staging
  on:
    repo: bkimminich/juice-shop
    node: 6
- provider: releases
  overwrite: true
  api_key:
    secure: fHybcH65ZdS5ITVKH2tIVBITVSiRQJ1AuWqLP16gyAz5pdmWbLM5gA/74zCozanRmuB+7pGFbhDNm075JWoEDVrWSFDLnNiXvfgUYa4oVEiWZlLvOfSARaU3AQPlVvFVhIbG9SA5IEwTtNFbyHjqLjGn/DSBpiIDqqxhF57vw7Q=
  file: dist/*
  skip_cleanup: true
  file_glob: true
  on:
    repo: bkimminich/juice-shop
    tags: true
sudo: required
