version: '{build}'
init:
  - git config --global core.autocrlf true
branches:
  except:
  - gh-pages
  - lightning-talk
  - l10n_develop
environment:
  matrix:
    - nodejs_version: 4
    - nodejs_version: 6 # recommended version
    - nodejs_version: 7
platform:
  - x64
install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - node --version && npm --version
  - if exist node_modules rd /Q /S node_modules # workaround for npm install bug missing module dependencies
  - npm cache clean
  - npm install --production
  - node_modules\.bin\grunt package
build: off
test: off
matrix:
  fast_finish: true
artifacts:
  - path: dist\*
deploy:
  - provider: GitHub
    draft: true
    auth_token:
      secure: bFkucwU1Zoh4EgzKmTAwONzQxuWPWrPGa+yXgadKQRd2jz5JPDZEw1f1vz2r+7i1
    on:
      appveyor_repo_tag: true
notifications:
## Disabled Gitter.im Webhook. Encrypted URLs currently not supported on AppVeyor.
## (see http://help.appveyor.com/discussions/problems/5225-encrypting-webhook-urls)
#  - provider: Webhook
#    url:
#      secure: c4xwvfA2YpTyASkpasFt2vA6q4pCxCMoWhfX9/JwBxp6rub4dphj6smGxy+5rnsHcvVU6/FvzVHQo4hoxL5gOA==
#    on_build_success: false
#    on_build_failure: true
#    on_build_status_changed: true
  - provider: Slack
    incoming_webhook:
      secure: KzO8e88B0LKqAI0BQM6lNhCIn9rxAava3AcdVJDyTw420OLIAlK+qzzbLXaR0jSH9zIJz9zu0iGS1iaqu9Co+6owYUrHJlBGrUZ/lZNCsDo=
    on_build_success: false
    on_build_failure: true
    on_build_status_changed: true
